FROM mcr.microsoft.com/dotnet/sdk:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY ["MedicalTrackingSystem.csproj", "./"]
RUN dotnet restore "MedicalTrackingSystem.csproj"
COPY . .

ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://+:80;https://+:443"] 